"""SETU Route Ranking v0.1 (Checkpoint 14).

Ranks physically plausible alternative candidate routes generated by Checkpoint 13
under available ETA, risk, accessibility, physical distance, and vehicle profile
compatibility signals.

Separation of Concerns:
- Candidate Generation (Checkpoint 13) answers: "What physically plausible routes exist?"
- Route Ranking (Checkpoint 14) answers: "Which candidate is preferable?"
- Explanation (Checkpoint 15) answers: "Why was this candidate ranked best?"
- Human Operator: Retains authority to review, approve, or reject reroute suggestions.

Strict Boundaries:
- Does NOT generate new routes or alter graph geometry.
- Does NOT reroute shipments or mutate operational state.
- Does NOT call external routing or traffic APIs (Mapbox, OSRM, Google Maps).
- Does NOT introduce ML, GA/PSO, databases, Kafka, Redis, or external microservices.
- Availability: Explicitly UNSUPPORTED in v0.1; never fabricated or simulated as false certainty.
- Vehicle Profile Compatibility Proxy: Reuses ETA engine vehicle profiles and surface/road
  hierarchy data. This is a profile compatibility proxy, NOT physical vehicle compatibility
  (no axle limits, bridge weight limits, or physical height clearances are fabricated).
- Risk Integrity: Risk scores MUST come strictly from precomputed candidate risk_score OR
  a COMPLETE explicit risk_context containing all 6 required Risk Engine fields.
  Missing risk inputs are NEVER fabricated, defaulted, or implicitly derived.
"""

from __future__ import annotations

import math
from types import MappingProxyType
from typing import Any, Dict, Iterable, List, Mapping, Optional, Set, Tuple

from src.accessibility.accessibility_scorer import calculate_accessibility
from src.eta.eta_engine import DEFAULT_SURFACE_MODIFIERS, DEFAULT_VEHICLE_PROFILES, estimate_route_eta
from src.risk.risk_engine import REQUIRED_FIELDS, calculate_risk

# Proportional weights based on approved blueprint ratios (30:20:20:15:10 over 95 total supported points).
# Availability is unsupported in v0.1 and excluded.
# The vehicle_profile_compatibility weight absorbs the residual float fraction so that
# sum(DEFAULT_RANKING_WEIGHTS.values()) == 1.0 exactly in IEEE 754 arithmetic.
_W_ETA = 30.0 / 95.0
_W_RISK = 20.0 / 95.0
_W_ACC = 20.0 / 95.0
_W_DIST = 15.0 / 95.0
_W_VEH = 1.0 - (_W_ETA + _W_RISK + _W_ACC + _W_DIST)

DEFAULT_RANKING_WEIGHTS: Mapping[str, float] = MappingProxyType({
    "eta": _W_ETA,
    "risk": _W_RISK,
    "accessibility": _W_ACC,
    "distance": _W_DIST,
    "vehicle_profile_compatibility": _W_VEH,
})

SUPPORTED_METRICS: Set[str] = {
    "eta",
    "risk",
    "accessibility",
    "distance",
    "vehicle_profile_compatibility",
}

# The 6 required Risk Engine fields that must all be present if evaluating risk from context
REQUIRED_RISK_CONTEXT_FIELDS: Tuple[str, ...] = (
    "incident_severity",
    "accessibility_score",
    "weather_severity",
    "road_condition_score",
    "network_criticality",
    "current_delay_ratio",
)


class RouteRankingValidationError(ValueError):
    """Raised when candidate records, metrics, weights, or risk context are invalid."""
    pass


def _validate_numeric(field: str, val: Any, min_val: float | None = None, max_val: float | None = None) -> float:
    """Validate that a value is a finite number within optional bounds."""
    if isinstance(val, bool) or not isinstance(val, (int, float)):
        raise RouteRankingValidationError(f"Field '{field}' must be numeric, got {type(val).__name__} ({val!r})")
    f_val = float(val)
    if not math.isfinite(f_val):
        raise RouteRankingValidationError(f"Field '{field}' must be finite, got {f_val}")
    if min_val is not None and f_val < min_val:
        raise RouteRankingValidationError(f"Field '{field}' must be >= {min_val}, got {f_val}")
    if max_val is not None and f_val > max_val:
        raise RouteRankingValidationError(f"Field '{field}' must be <= {max_val}, got {f_val}")
    return f_val


def _compute_vehicle_profile_compatibility_proxy(
    segments: List[Dict[str, Any]],
    vehicle_profile: Optional[str] = None,
    vehicle_speed_factor: Optional[float] = None,
) -> float:
    """Compute deterministic vehicle profile compatibility proxy.

    DISCLOSURE: This is a vehicle profile compatibility proxy based on OSM
    surface and road hierarchy data recognized by SETU ETA Engine v0.1,
    NOT physical vehicle compatibility (such as axle weight, bridge limits, or clearance).

    Heavy trucks experience reduced compatibility on unpaved surfaces; passenger and
    light commercial vehicles maintain higher compatibility across road tiers.
    """
    if not segments:
        return 1.0

    # Resolve vehicle multiplier
    factor = 1.0
    if vehicle_speed_factor is not None:
        factor = float(vehicle_speed_factor)
    elif vehicle_profile is not None:
        clean_name = str(vehicle_profile).strip().lower()
        if clean_name in DEFAULT_VEHICLE_PROFILES:
            factor = float(DEFAULT_VEHICLE_PROFILES[clean_name])

    # Distance-weighted surface score across segments
    total_len = sum(float(s.get("segment_length_km", 0.0)) for s in segments)
    if total_len <= 0.0:
        return 1.0

    weighted_surface = 0.0
    for s in segments:
        length = float(s.get("segment_length_km", 0.0))
        surface_str = str(s.get("surface", "")).strip().lower()
        surf_mod = DEFAULT_SURFACE_MODIFIERS.get(surface_str, 1.0)

        # For heavy vehicles (speed factor < 1.0), penalize degraded/unpaved surfaces more sharply
        if factor < 1.0:
            compatibility = surf_mod ** 1.5
        else:
            compatibility = surf_mod

        weighted_surface += compatibility * length

    score = weighted_surface / total_len
    return round(max(0.0, min(1.0, score)), 4)


def _evaluate_candidate_signals(
    candidate: Mapping[str, Any],
    risk_context: Optional[Mapping[str, Any]],
    vehicle_profile: Optional[str],
    vehicle_speed_factor: Optional[float],
) -> Dict[str, float]:
    """Evaluate or extract the 5 ranking signals for a single candidate.

    Signals:
    1. eta_seconds: float >= 0.0 (lower is better)
    2. risk_score: float [0, 100] (lower is better)
    3. accessibility_score: float [0, 1] (higher is better)
    4. distance_km: float >= 0.0 (lower is better)
    5. vehicle_profile_compatibility: float [0, 1] (higher is better)
    """
    route_id = str(candidate.get("route_id", "")).strip()

    # 1. Distance
    if "total_distance_km" not in candidate or candidate["total_distance_km"] is None:
        raise RouteRankingValidationError(f"Candidate '{route_id}' missing 'total_distance_km'")
    distance_km = _validate_numeric(f"{route_id}.total_distance_km", candidate["total_distance_km"], min_val=0.0)

    segments: List[Dict[str, Any]] = list(candidate.get("segments", []))

    # 2. ETA
    if "eta_seconds" in candidate and candidate["eta_seconds"] is not None:
        eta_seconds = _validate_numeric(f"{route_id}.eta_seconds", candidate["eta_seconds"], min_val=0.0)
    elif segments:
        eta_res = estimate_route_eta(
            segments,
            vehicle_profile=vehicle_profile,
            vehicle_speed_factor=vehicle_speed_factor,
        )
        eta_seconds = float(eta_res["disrupted_eta_seconds"])
    else:
        # 0 distance / empty segments degenerate route
        eta_seconds = 0.0

    # 3. Accessibility
    if "accessibility_score" in candidate and candidate["accessibility_score"] is not None:
        acc_score = _validate_numeric(f"{route_id}.accessibility_score", candidate["accessibility_score"], 0.0, 1.0)
    elif segments:
        total_len = sum(float(s.get("segment_length_km", 0.0)) for s in segments)
        acc_weighted = 0.0
        for s in segments:
            acc_eval = calculate_accessibility(s)
            length = float(s.get("segment_length_km", 0.0))
            acc_weighted += float(acc_eval["accessibility_score"]) * (length if total_len > 0.0 else 1.0)
        acc_score = acc_weighted / (total_len if total_len > 0.0 else len(segments))
        acc_score = round(max(0.0, min(1.0, acc_score)), 4)
    else:
        acc_score = 1.0

    # 4. Risk Integrity (Precomputed candidate risk_score OR complete explicit risk_context; NEVER fabricated)
    if "risk_score" in candidate and candidate["risk_score"] is not None:
        risk_score = _validate_numeric(f"{route_id}.risk_score", candidate["risk_score"], 0.0, 100.0)
    elif risk_context is not None:
        if not isinstance(risk_context, Mapping):
            raise RouteRankingValidationError(f"Expected risk_context to be a mapping, got {type(risk_context).__name__}")

        # Check ALL 6 required Risk Engine fields explicitly
        missing_risk_fields = [
            rf for rf in REQUIRED_RISK_CONTEXT_FIELDS if rf not in risk_context or risk_context[rf] is None
        ]
        if missing_risk_fields:
            raise RouteRankingValidationError(
                f"Candidate '{route_id}' requires risk evaluation, but risk_context is missing required field(s): "
                f"{sorted(missing_risk_fields)}. Risk inputs must never be fabricated, defaulted, or implicitly derived."
            )

        # Strictly validate all 6 inputs without defaulting or implicit derivations
        risk_inputs = {
            rf: _validate_numeric(f"risk_context.{rf}", risk_context[rf], 0.0, 1.0)
            for rf in REQUIRED_RISK_CONTEXT_FIELDS
        }
        risk_res = calculate_risk(risk_inputs)
        risk_score = float(risk_res["risk_score"])
    else:
        raise RouteRankingValidationError(
            f"Candidate '{route_id}' has no precomputed 'risk_score' and no complete 'risk_context' was provided. "
            "Risk inputs must strictly come from candidate.risk_score or complete explicit risk_context."
        )

    # 5. Vehicle Profile Compatibility Proxy
    if "vehicle_profile_compatibility" in candidate and candidate["vehicle_profile_compatibility"] is not None:
        veh_score = _validate_numeric(
            f"{route_id}.vehicle_profile_compatibility",
            candidate["vehicle_profile_compatibility"],
            0.0,
            1.0,
        )
    elif "vehicle_fit" in candidate and candidate["vehicle_fit"] is not None:
        # Backwards-compatible field alias
        veh_score = _validate_numeric(f"{route_id}.vehicle_fit", candidate["vehicle_fit"], 0.0, 1.0)
    else:
        veh_score = _compute_vehicle_profile_compatibility_proxy(
            segments,
            vehicle_profile=vehicle_profile,
            vehicle_speed_factor=vehicle_speed_factor,
        )

    return {
        "eta_seconds": round(eta_seconds, 3),
        "risk_score": round(risk_score, 2),
        "accessibility_score": round(acc_score, 4),
        "distance_km": round(distance_km, 6),
        "vehicle_profile_compatibility": round(veh_score, 4),
    }


def rank_route_candidates(
    candidates: Iterable[Mapping[str, Any]],
    risk_context: Optional[Mapping[str, Any]] = None,
    vehicle_profile: Optional[str] = None,
    vehicle_speed_factor: Optional[float] = None,
    custom_weights: Optional[Mapping[str, float]] = None,
) -> List[Dict[str, Any]]:
    """Rank physically plausible candidate routes using deterministic normalized utility.

    Evaluates and normalizes 5 signals:
    - ETA: Lower is better (Cost)
    - Risk: Lower is better (Cost)
    - Accessibility: Higher is better (Benefit)
    - Distance: Lower is better (Cost)
    - Vehicle Profile Compatibility: Higher is better (Benefit)

    Availability is explicitly unsupported in v0.1 and not fabricated.

    Args:
        candidates: Non-empty iterable of candidate route mappings (from Checkpoint 13).
        risk_context: Required if candidates do not already contain precomputed 'risk_score'.
            Must provide all 6 required fields: incident_severity, accessibility_score,
            weather_severity, road_condition_score, network_criticality, current_delay_ratio.
        vehicle_profile: Optional vehicle profile name ('standard_truck', 'heavy_truck', etc.).
        vehicle_speed_factor: Optional custom positive numeric speed factor.
        custom_weights: Optional mapping overriding DEFAULT_RANKING_WEIGHTS.

    Returns:
        List of ranked candidate route records sorted from Rank 1 (best) to Rank N.
    """
    if candidates is None:
        raise RouteRankingValidationError("Expected candidates to be an iterable collection, got None")
    if isinstance(candidates, (str, bytes, Mapping)):
        raise RouteRankingValidationError(f"Expected candidates to be an iterable collection of mappings, got {type(candidates).__name__}")

    try:
        cand_list = list(candidates)
    except TypeError as exc:
        raise RouteRankingValidationError(f"Expected candidates to be iterable, got {type(candidates).__name__}") from exc

    if not cand_list:
        raise RouteRankingValidationError("Cannot rank an empty candidate collection")

    # Validate custom weights or use default
    weights_dict: Dict[str, float] = {}
    if custom_weights is not None:
        if not isinstance(custom_weights, Mapping):
            raise RouteRankingValidationError(f"Expected custom_weights to be a mapping, got {type(custom_weights).__name__}")

        # Strict validation: Reject unknown keys in custom_weights
        unknown_keys = set(custom_weights.keys()) - SUPPORTED_METRICS
        if unknown_keys:
            raise RouteRankingValidationError(
                f"Unknown key(s) in custom_weights: {sorted(unknown_keys)}. "
                f"Supported metrics are: {sorted(SUPPORTED_METRICS)}"
            )

        for k in SUPPORTED_METRICS:
            if k in custom_weights:
                weights_dict[k] = _validate_numeric(f"custom_weights.{k}", custom_weights[k], min_val=0.0)
            else:
                weights_dict[k] = DEFAULT_RANKING_WEIGHTS[k]
        w_sum = sum(weights_dict.values())
        if w_sum <= 0.0:
            raise RouteRankingValidationError("Sum of custom weights must be strictly positive")
        weights_dict = {k: v / w_sum for k, v in weights_dict.items()}
    else:
        weights_dict = dict(DEFAULT_RANKING_WEIGHTS)

    # 1. Extract raw metrics for all candidates without mutating inputs
    extracted_records: List[Dict[str, Any]] = []
    seen_route_ids: Set[str] = set()

    for raw_cand in cand_list:
        if not isinstance(raw_cand, Mapping):
            raise RouteRankingValidationError(f"Expected candidate to be a mapping, got {type(raw_cand).__name__}")

        route_id = raw_cand.get("route_id")
        if route_id is None or not str(route_id).strip():
            raise RouteRankingValidationError("Every candidate must contain a non-empty 'route_id'")
        route_id_str = str(route_id).strip()

        if route_id_str in seen_route_ids:
            raise RouteRankingValidationError(f"Duplicate route_id '{route_id_str}' in candidates collection")
        seen_route_ids.add(route_id_str)

        signals = _evaluate_candidate_signals(raw_cand, risk_context, vehicle_profile, vehicle_speed_factor)

        # Shallow copy to preserve caller's input dictionary immutability
        cand_copy = dict(raw_cand)
        cand_copy["route_id"] = route_id_str
        extracted_records.append({
            "candidate": cand_copy,
            "metrics": signals,
        })

    # 2. Determine metric bounds across the candidate set for min-max utility normalization
    all_eta = [r["metrics"]["eta_seconds"] for r in extracted_records]
    all_risk = [r["metrics"]["risk_score"] for r in extracted_records]
    all_acc = [r["metrics"]["accessibility_score"] for r in extracted_records]
    all_dist = [r["metrics"]["distance_km"] for r in extracted_records]
    all_veh = [r["metrics"]["vehicle_profile_compatibility"] for r in extracted_records]

    min_eta, max_eta = min(all_eta), max(all_eta)
    min_risk, max_risk = min(all_risk), max(all_risk)
    min_acc, max_acc = min(all_acc), max(all_acc)
    min_dist, max_dist = min(all_dist), max(all_dist)
    min_veh, max_veh = min(all_veh), max(all_veh)

    # 3. Calculate normalized utility scores and composite ranking score
    evaluated_candidates: List[Dict[str, Any]] = []

    for item in extracted_records:
        cand = item["candidate"]
        m = item["metrics"]

        # Cost metrics: lower is better (min -> 1.0, max -> 0.0)
        u_eta = 1.0 if math.isclose(max_eta, min_eta, abs_tol=1e-9) else (max_eta - m["eta_seconds"]) / (max_eta - min_eta)
        u_risk = 1.0 if math.isclose(max_risk, min_risk, abs_tol=1e-9) else (max_risk - m["risk_score"]) / (max_risk - min_risk)
        u_dist = 1.0 if math.isclose(max_dist, min_dist, abs_tol=1e-9) else (max_dist - m["distance_km"]) / (max_dist - min_dist)

        # Benefit metrics: higher is better (max -> 1.0, min -> 0.0)
        u_acc = 1.0 if math.isclose(max_acc, min_acc, abs_tol=1e-9) else (m["accessibility_score"] - min_acc) / (max_acc - min_acc)
        u_veh = 1.0 if math.isclose(max_veh, min_veh, abs_tol=1e-9) else (m["vehicle_profile_compatibility"] - min_veh) / (max_veh - min_veh)

        # Clamping utilities [0, 1] for absolute safety
        u_eta = max(0.0, min(1.0, u_eta))
        u_risk = max(0.0, min(1.0, u_risk))
        u_acc = max(0.0, min(1.0, u_acc))
        u_dist = max(0.0, min(1.0, u_dist))
        u_veh = max(0.0, min(1.0, u_veh))

        # Composite score
        score = (
            weights_dict["eta"] * u_eta
            + weights_dict["risk"] * u_risk
            + weights_dict["accessibility"] * u_acc
            + weights_dict["distance"] * u_dist
            + weights_dict["vehicle_profile_compatibility"] * u_veh
        )
        ranking_score = round(max(0.0, min(1.0, score)), 4)

        tradeoff_summary = {
            "is_fastest": math.isclose(m["eta_seconds"], min_eta, abs_tol=1e-6),
            "is_lowest_risk": math.isclose(m["risk_score"], min_risk, abs_tol=1e-6),
            "is_most_accessible": math.isclose(m["accessibility_score"], max_acc, abs_tol=1e-6),
            "is_shortest": math.isclose(m["distance_km"], min_dist, abs_tol=1e-6),
            "is_best_vehicle_profile_compatibility": math.isclose(m["vehicle_profile_compatibility"], max_veh, abs_tol=1e-6),
        }

        record = dict(cand)
        record.update({
            "ranking_score": ranking_score,
            "metrics": m,
            "normalized_scores": {
                "eta_score": round(u_eta, 4),
                "risk_score": round(u_risk, 4),
                "accessibility_score": round(u_acc, 4),
                "distance_score": round(u_dist, 4),
                "vehicle_profile_compatibility_score": round(u_veh, 4),
            },
            "weights_applied": dict(weights_dict),
            "tradeoff_summary": tradeoff_summary,
        })
        evaluated_candidates.append(record)

    # 4. Deterministic Sort and Tie-Breaking:
    # 1. ranking_score (descending: higher score = better rank)
    # 2. physical distance (ascending: shorter distance preferred)
    # 3. segment_count (ascending: simpler route with fewer segments preferred)
    # 4. segment_ids (lexicographical tuple)
    # 5. node_ids (lexicographical tuple)
    # 6. route_id (lexicographical string)
    evaluated_candidates.sort(
        key=lambda c: (
            -c["ranking_score"],
            c["metrics"]["distance_km"],
            c.get("segment_count", len(c.get("segment_ids", []))),
            tuple(str(sid) for sid in c.get("segment_ids", [])),
            tuple(str(nid) for nid in c.get("node_ids", [])),
            c["route_id"],
        )
    )

    # 5. Assign 1-based ranks
    for idx, cand_record in enumerate(evaluated_candidates, start=1):
        cand_record["rank"] = idx

    return evaluated_candidates
