"""SETU_AI — Machine Learning (ML) Package (Checkpoint 19).

Provides supervised baseline model architectures, memory-safe data ingestion,
canonical feature extraction, train-only preprocessing, deterministic positive-preserving
sampling, threshold tuning, and temporal generalization evaluation.
"""

from __future__ import annotations

from src.ml.train_models import (
    ARTIFACT_PATHS,
    CANONICAL_FEATURES,
    EVALUATION_SUMMARY_PATH,
    FORBIDDEN_LEAKAGE_COLUMNS,
    HIST_GRADIENT_BOOSTING_ARTIFACT_PATH,
    LINEAR_BASELINE_ARTIFACT_PATH,
    MODEL_COMPARISON_REPORT_PATH,
    MODELS_DIR,
    RANDOM_FOREST_ARTIFACT_PATH,
    RANDOM_SEED,
    SCALER_ARTIFACT_PATH,
    SCALER_METADATA_PATH,
    TARGET_COLUMN,
    TEST_YEARS,
    TRAIN_YEARS,
    VAL_YEARS,
    build_hist_gradient_boosting,
    build_logistic_regression,
    build_random_forest,
    build_sgd_classifier,
    check_pipeline_resource_diagnostics,
    compute_evaluation_metrics,
    count_partition_rows,
    derive_cyclical_temporal_features,
    encode_weather_code,
    evaluate_temporal_test,
    extract_feature_vector,
    fit_hist_gradient_boosting,
    fit_linear_baseline_with_fallback,
    fit_linear_scaler,
    generate_model_comparison_report,
    get_model_probabilities,
    get_split_name,
    load_split_matrix,
    prepare_model_input,
    run_training_pipeline,
    sample_rf_training_data,
    save_pipeline_artifacts,
    select_champion_model,
    tune_validation_threshold,
)
from src.ml.inference import (
    FROZEN_DECISION_THRESHOLD,
    DisruptionInferenceEngine,
    MLInferenceRuntimeError,
    MLInferenceValidationError,
    ModelArtifactNotFoundError,
    construct_feature_vector_from_context,
    get_default_inference_engine,
    predict_route_disruption,
    predict_segment_disruption,
    predict_segments_disruption,
)

__all__ = [
    "CANONICAL_FEATURES",
    "TARGET_COLUMN",
    "RANDOM_SEED",
    "TRAIN_YEARS",
    "VAL_YEARS",
    "TEST_YEARS",
    "FORBIDDEN_LEAKAGE_COLUMNS",
    "extract_feature_vector",
    "derive_cyclical_temporal_features",
    "encode_weather_code",
    "get_split_name",
    "fit_linear_scaler",
    "prepare_model_input",
    "sample_rf_training_data",
    "tune_validation_threshold",
    "compute_evaluation_metrics",
    "evaluate_temporal_test",
    "build_logistic_regression",
    "build_sgd_classifier",
    "build_random_forest",
    "build_hist_gradient_boosting",
    "fit_linear_baseline_with_fallback",
    "fit_hist_gradient_boosting",
    "select_champion_model",
    "MODELS_DIR",
    "SCALER_ARTIFACT_PATH",
    "SCALER_METADATA_PATH",
    "LINEAR_BASELINE_ARTIFACT_PATH",
    "RANDOM_FOREST_ARTIFACT_PATH",
    "HIST_GRADIENT_BOOSTING_ARTIFACT_PATH",
    "EVALUATION_SUMMARY_PATH",
    "MODEL_COMPARISON_REPORT_PATH",
    "ARTIFACT_PATHS",
    "count_partition_rows",
    "load_split_matrix",
    "get_model_probabilities",
    "generate_model_comparison_report",
    "save_pipeline_artifacts",
    "check_pipeline_resource_diagnostics",
    "run_training_pipeline",
    "DisruptionInferenceEngine",
    "ModelArtifactNotFoundError",
    "MLInferenceValidationError",
    "MLInferenceRuntimeError",
    "FROZEN_DECISION_THRESHOLD",
    "predict_segment_disruption",
    "predict_segments_disruption",
    "predict_route_disruption",
    "construct_feature_vector_from_context",
    "get_default_inference_engine",
]
